Repository second-hand-team06/second-hand, pull requests merged in 2023-06, with the labels that each got.

#3 [FE] merge 작업
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/craco.config.ts
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/logo.svg
  fe/src/react-app-env.d.ts
  fe/src/reportWebVitals.ts
  fe/src/setupTests.ts
  fe/tsconfig.json
Labels: 🧑‍💻 FE, 🔧 chore

#4 [FE] croco 초기 환경 설정
  fe/.eslintrc.json
  fe/craco.config.js
  fe/craco.config.ts
  fe/package.json
  fe/tsconfig.json
  fe/tsconfig.paths.json
Labels: 🧑‍💻 FE, 🔧 chore

#6 [FE] router 설정
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.css
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/logo.svg
  fe/src/pages/Home/index.jsx
  fe/src/pages/Home/style.js
  fe/src/pages/NeighborhoodSetting/index.jsx
  fe/src/pages/NeighborhoodSetting/style.js
Labels: 🧑‍💻 FE, 🔧 chore

#9 [BE] swagger 설정
  be/build.gradle
  be/src/main/java/com/secondhand/config/SwaggerConfig.java
Labels: 🧑‍💻 BE, ✨ feat

#10 Fe feat/#7 theme
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.css
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/context/themeContext.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/logo.svg
  fe/src/pages/Home/index.jsx
  fe/src/pages/Home/style.js
  fe/src/pages/NeighborhoodSetting/index.jsx
  fe/src/pages/NeighborhoodSetting/style.js
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/color.ts
  fe/src/styles/font.ts
  fe/tsconfig.paths.json
Labels: 🧑‍💻 FE, ✨ feat

#15 [FE] theme 설정
  fe/src/App.tsx
  fe/src/context/themeContext.tsx
  fe/src/pages/Home/index.jsx
  fe/src/styles/GlobalStyle.ts
  fe/src/styles/color.ts
  fe/src/styles/font.ts
  fe/tsconfig.paths.json
Labels: 🧑‍💻 FE, ✨ feat

#37 [FE] ProductListItem 컴포넌트 생성 및 useIntersectionObserver 커스텀 훅 생성
  fe/src/assets/arrowUp.svg
  fe/src/assets/camera.svg
  fe/src/assets/chevronDown.svg
  fe/src/assets/chevronLeft.svg
  fe/src/assets/circleFill.svg
  fe/src/assets/ellipsis.svg
  fe/src/assets/hamburger.svg
  fe/src/assets/home.svg
  fe/src/assets/keyboard.svg
  fe/src/assets/like.svg
  fe/src/assets/message.svg
  fe/src/assets/multiply.svg
  fe/src/assets/newspaper.svg
  fe/src/assets/person.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/components/ProductListItem/index.tsx
  fe/src/components/ProductListItem/style.ts
  fe/src/components/common/Icon/index.tsx
  fe/src/hooks/useFetch.ts
  fe/src/hooks/useIntersectionObserver.ts
  fe/src/pages/Home/index.tsx
  fe/src/pages/Home/style.js
  fe/src/pages/Home/style.ts
  fe/src/pages/NeighborhoodSetting/index.tsx
  fe/src/pages/NeighborhoodSetting/style.js
  fe/src/pages/NeighborhoodSetting/style.ts
  fe/src/styles/color.ts
Labels: 🧑‍💻 FE, ✨ feat

#44 [BE] 로그인 검증을 위한 interceptor 활용 예정
  be/build.gradle
  be/src/main/java/com/secondhand/config/WebConfig.java
  be/src/main/java/com/secondhand/interceptor/LoginInterceptor.java
  be/src/main/java/com/secondhand/user/entity/User.java
  be/src/main/java/com/secondhand/user/login/JwtUtil.java
  be/src/main/java/com/secondhand/user/login/LoginController.java
  be/src/main/java/com/secondhand/user/login/LoginService.java
  be/src/main/java/com/secondhand/user/login/dto/GithubToken.java
  be/src/main/java/com/secondhand/user/login/dto/JWTResponse.java
  be/src/main/java/com/secondhand/user/login/dto/UserProfileResponse.java
  be/src/main/java/com/secondhand/user/repository/UserRepository.java
Labels: 🧑‍💻 BE, ✨ feat

#45 [FE] craco-alias 삭제 및 react-app-alias 설치
  fe/craco.config.js
  fe/package-lock.json
  fe/package.json
Labels: 🧑‍💻 FE, 🔧 chore

#48 [BE] 내 동네 수정/삭제 하기 기능 구현
  be/src/main/java/com/secondhand/region/RegionController.java
  be/src/main/java/com/secondhand/region/RegionService.java
  be/src/main/java/com/secondhand/region/dto/PostMyRegionDto.java
  be/src/main/java/com/secondhand/user/UserController.java
  be/src/main/java/com/secondhand/user/UserService.java
  be/src/main/java/com/secondhand/user/entity/User.java
  be/src/main/java/com/secondhand/user/login/JwtUtil.java
  be/src/main/java/com/secondhand/user/login/LoginController.java
Labels: 🧑‍💻 BE, ✨ feat

#49 [BE] 내 동네 수정 기능 및 상품 목록 조회 버그 수정 후 배포
  be/src/main/java/com/secondhand/post/dto/PostMetaDto.java
  be/src/main/java/com/secondhand/post/repository/PostRepositoryImpl.java
  be/src/main/java/com/secondhand/region/RegionController.java
  be/src/main/java/com/secondhand/region/RegionService.java
  be/src/main/java/com/secondhand/region/dto/PostMyRegionDto.java
  be/src/main/java/com/secondhand/user/UserController.java
  be/src/main/java/com/secondhand/user/UserService.java
  be/src/main/java/com/secondhand/user/entity/User.java
  be/src/main/java/com/secondhand/user/login/JwtUtil.java
  be/src/main/java/com/secondhand/user/login/LoginController.java
Labels: 🐛 fix, 🧑‍💻 BE, ✨ feat

#50 [BE] 이미지 파일 업로드 메서드 구현(#28)
  be/src/main/java/com/secondhand/fileupload/FileUploadService.java
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/dto/PostSaveDto.java
Labels: 🧑‍💻 BE, ✨ feat

#53 [FE] 버튼 공통 컴포넌트 구현
  fe/src/components/common/Button/index.tsx
  fe/src/components/common/Button/style.ts
Labels: 🧑‍💻 FE, ✨ feat

#54 [FE] TabBar 컴포넌트 생성
  fe/src/App.tsx
  fe/src/components/TabBar/index.tsx
  fe/src/components/TabBar/style.ts
  fe/src/pages/Chatting/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/Interests/index.tsx
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/Sales/index.tsx
  fe/src/styles/color.ts
Labels: 🧑‍💻 FE, ✨ feat

#58 [BE] 판매글 생성 시 content, photos 데이터베이스 및 S3에 추가(#57)
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/entity/PostDetail.java
  be/src/main/java/com/secondhand/post/entity/PostPhoto.java
  be/src/main/java/com/secondhand/post/repository/PostDetailRepository.java
  be/src/main/java/com/secondhand/post/repository/PostMetaRepository.java
  be/src/main/java/com/secondhand/post/repository/PostMetaRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/PostMetaRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/PostPhotoRepository.java
Labels: 🧑‍💻 BE, ✨ feat

#64 [BE] 관심 목록 상품 카테고리 조회
  be/src/main/java/com/secondhand/category/CategoryController.java
  be/src/main/java/com/secondhand/category/dto/CategoryInInterestDto.java
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/repository/InterestRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/InterestRepositoryImpl.java
Labels: 🧑‍💻 BE, ✨ feat

#65 [BE] 관심상품목록 카테고리 리스트를 담는 dto 추가 (#63)
  be/src/main/java/com/secondhand/category/CategoryController.java
  be/src/main/java/com/secondhand/category/dto/CategoryInterestsDto.java
Labels: 🧑‍💻 BE, ✨ feat

#66 [BE] feat/#32 edit post
  be/src/main/java/com/secondhand/fileupload/FileUploadService.java
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/dto/PostUpdateDto.java
  be/src/main/java/com/secondhand/post/entity/PostDetail.java
  be/src/main/java/com/secondhand/post/entity/PostMeta.java
  be/src/main/java/com/secondhand/post/repository/PostPhotoRepository.java
Labels: 🧑‍💻 BE, ✨ feat

#67 [BE] feat: 상품 삭제 기능 구현(#33)
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/entity/PostMeta.java
Labels: 🧑‍💻 BE, ✨ feat

#68 [BE] feat: 상품 상태 수정 기능 구현(#35)
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/dto/UpdatePostStateDto.java
  be/src/main/java/com/secondhand/post/entity/PostMeta.java
Labels: 🧑‍💻 BE, ✨ feat

#69 [BE] feat: 관심 상품 추가(#34)
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/entity/Interest.java
  be/src/main/java/com/secondhand/user/UserController.java
  be/src/main/java/com/secondhand/user/UserService.java
Labels: 🧑‍💻 BE, ✨ feat

#71 [BE] feat: 관심 상품 목록에서 관심 상품 삭제하기 기능 구현(#70)
  be/src/main/java/com/secondhand/post/repository/InterestRepository.java
  be/src/main/java/com/secondhand/post/repository/InterestRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/InterestRepositoryImpl.java
  be/src/main/java/com/secondhand/user/UserController.java
  be/src/main/java/com/secondhand/user/UserService.java
Labels: 🧑‍💻 BE, ✨ feat

#73 [BE] feat: 뱃지 목록 조회 기능 구현(#72)
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/dto/BadgesDto.java
Labels: 🧑‍💻 BE, ✨ feat

#74 [BE] feat/#36 find categories
  be/src/main/java/com/secondhand/category/CategoryController.java
  be/src/main/java/com/secondhand/category/CategoryService.java
  be/src/main/java/com/secondhand/category/dto/CategoriesDto.java
  be/src/main/java/com/secondhand/category/dto/CategoryDto.java
  be/src/main/java/com/secondhand/post/repository/CategoryRepository.java
  be/src/main/java/com/secondhand/post/repository/CategoryRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/CategoryRepositoryImpl.java
Labels: 🧑‍💻 BE, ✨ feat

#76 [Be] feat/#75 recommend categories
  be/src/main/java/com/secondhand/category/CategoryController.java
  be/src/main/java/com/secondhand/category/CategoryService.java
  be/src/main/java/com/secondhand/category/dto/CategoriesDto.java
  be/src/main/java/com/secondhand/category/dto/PostTitleDto.java
  be/src/main/java/com/secondhand/category/dto/RecommendedCategoriesDto.java
  be/src/main/java/com/secondhand/category/dto/RecommendedCategoryDto.java
  be/src/main/java/com/secondhand/post/repository/CategoryRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/CategoryRepositoryImpl.java
Labels: 🧑‍💻 BE, ✨ feat

#77 [BE] feat/#31 상품 상세 페이지 조회
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/dto/PostDetailDto.java
  be/src/main/java/com/secondhand/post/dto/PostDetailPageDto.java
  be/src/main/java/com/secondhand/post/entity/PostDetail.java
  be/src/main/java/com/secondhand/post/entity/PostMeta.java
  be/src/main/java/com/secondhand/post/repository/PostMetaRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/PostMetaRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/PostPhotoRepository.java
  be/src/main/java/com/secondhand/post/repository/PostPhotoRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/PostPhotoRepositoryImpl.java
Labels: 🧑‍💻 BE, ✨ feat

#78 [BE] feat: 상품 상세 조회 시 관심상품으로 등록한 유저 수 추가(#31)
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/dto/PostDetailPageDto.java
  be/src/main/java/com/secondhand/post/repository/InterestRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/InterestRepositoryImpl.java
Labels: 🧑‍💻 BE, ✨ feat

#80 [BE] refactor/#21 로그인 권한 예외 처리
  be/src/main/java/com/secondhand/config/WebConfig.java
  be/src/main/java/com/secondhand/exception/GlobalExceptionHandler.java
  be/src/main/java/com/secondhand/exception/post/PostAuthorizationException.java
  be/src/main/java/com/secondhand/exception/post/PostOwnershipMismatchException.java
  be/src/main/java/com/secondhand/interceptor/CreatePostInterceptor.java
  be/src/main/java/com/secondhand/interceptor/LoginInterceptor.java
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/entity/PostMeta.java
  be/src/main/java/com/secondhand/post/validator/PostValidator.java
  be/src/main/java/com/secondhand/user/login/JwtUtil.java
  be/src/main/resources/application.yml
Labels: 🧑‍💻 BE, ✨ feat

#81 [FE] ProductList 컴포넌트 생성
  fe/src/components/ProductList/index.tsx
  fe/src/components/ProductList/style.ts
  fe/src/components/ProductListItem/index.tsx
  fe/src/components/ProductListItem/style.ts
  fe/src/hooks/useFetch.ts
  fe/src/hooks/useIntersectionObserver.ts
  fe/src/pages/Home/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#83 [BE] jwt 로그인 테스트
  be/src/main/java/com/secondhand/user/login/JwtUtil.java
  be/src/main/java/com/secondhand/user/login/LoginController.java
  be/src/test/java/com/secondhand/user/login/JwtUtilTest.java
Labels: 🧑‍💻 BE, ✅ test

#88 [FE] Home 컴포넌트 View 생성
  fe/src/App.tsx
  fe/src/components/ProductList/index.tsx
  fe/src/components/ProductListItem/index.tsx
  fe/src/components/TabBar/style.ts
  fe/src/components/common/Header/index.tsx
  fe/src/components/common/Header/style.ts
  fe/src/hooks/useFetch.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/utils/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#89 [FE] 로그인 기능 구현
  fe/src/App.tsx
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/MyAccount/style.ts
  fe/src/pages/Oauth.tsx
  fe/src/styles/color.ts
Labels: 🧑‍💻 FE, ✨ feat

#90 [BE] refactor/#84 post crud
  be/src/main/java/com/secondhand/category/CategoryController.java
  be/src/main/java/com/secondhand/category/CategoryService.java
  be/src/main/java/com/secondhand/config/WebConfig.java
  be/src/main/java/com/secondhand/exception/GlobalExceptionHandler.java
  be/src/main/java/com/secondhand/interceptor/CreatePostInterceptor.java
  be/src/main/java/com/secondhand/interceptor/LoginInterceptor.java
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/dto/UpdatePostStateDto.java
  be/src/main/java/com/secondhand/post/entity/Badge.java
  be/src/main/java/com/secondhand/post/entity/Category.java
  be/src/main/java/com/secondhand/post/entity/PostMeta.java
  be/src/main/java/com/secondhand/post/repository/PostMetaRepository.java
  be/src/main/java/com/secondhand/post/repository/badge/BadgeRepository.java
  be/src/main/java/com/secondhand/post/repository/category/CategoryRepository.java
  be/src/main/java/com/secondhand/post/repository/category/CategoryRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/category/CategoryRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/interest/InterestRepository.java
  be/src/main/java/com/secondhand/post/repository/interest/InterestRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/interest/InterestRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/postdetail/PostDetailRepository.java
  be/src/main/java/com/secondhand/post/repository/postmeta/PostMetaRepository.java
  be/src/main/java/com/secondhand/post/repository/postmeta/PostMetaRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/postmeta/PostMetaRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/postphoto/PostPhotoRepository.java
  be/src/main/java/com/secondhand/post/repository/postphoto/PostPhotoRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/postphoto/PostPhotoRepositoryImpl.java
  be/src/main/java/com/secondhand/post/validator/PostValidator.java
  be/src/main/java/com/secondhand/region/RegionService.java
  be/src/main/java/com/secondhand/region/dto/PostMyRegionDto.java
  be/src/main/java/com/secondhand/region/entity/Region.java
  be/src/main/java/com/secondhand/region/validator/RegionValidator.java
  be/src/main/java/com/secondhand/user/UserController.java
  be/src/main/java/com/secondhand/user/UserService.java
  be/src/main/java/com/secondhand/user/entity/User.java
  be/src/main/java/com/secondhand/user/login/dto/LoggedInUser.java
  be/src/test/java/com/secondhand/post/PostControllerTest.java
  be/src/test/java/com/secondhand/post/PostServiceTest.java
  be/src/test/java/com/secondhand/post/repository/postmeta/PostMetaRepositoryImplTest.java
  be/src/test/java/com/secondhand/post/repository/postmeta/PostMetaRepositoryTest.java
Labels: 🧑‍💻 BE, ♻️ refactor

#94 [FE] Home 페이지 View 생성
  fe/src/App.tsx
  fe/src/components/ProductList/index.tsx
  fe/src/components/ProductList/style.ts
  fe/src/components/ProductListItem/style.ts
  fe/src/components/TabBar/style.ts
  fe/src/components/common/Button/Button.stories.tsx
  fe/src/components/common/Button/index.tsx
  fe/src/components/common/Button/style.ts
  fe/src/components/common/Header/index.tsx
  fe/src/components/common/Header/style.ts
  fe/src/pages/Home/index.tsx
  fe/src/pages/Home/style.ts
  fe/src/pages/NewProduct/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#96 [FE] Header 공통 컴포넌트 생성
  fe/.storybook/preview.tsx
  fe/src/components/common/Header/Header.stories.ts
  fe/src/components/common/Header/HomeHeader/index.tsx
  fe/src/components/common/Header/HomeHeader/style.ts
  fe/src/components/common/Header/SalesHeader/index.tsx
  fe/src/components/common/Header/SalesHeader/style.ts
  fe/src/components/common/Header/SearchHeader/index.tsx
  fe/src/components/common/Header/SearchHeader/style.ts
  fe/src/components/common/Header/index.tsx
  fe/src/components/common/Header/style.ts
  fe/src/pages/Home/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#102 [FE] useFetch 상태 분리
  fe/src/components/ProductList/index.tsx
  fe/src/constants/index.ts
  fe/src/hooks/useFetch.ts
  fe/src/pages/LoginLoading/index.tsx
Labels: 🧑‍💻 FE, ♻️ refactor

#107 [Be] refactor/#105 refactor jwt data
  be/src/main/java/com/secondhand/region/dto/RegionDto.java
  be/src/main/java/com/secondhand/region/repository/RegionRepository.java
  be/src/main/java/com/secondhand/user/UserController.java
  be/src/main/java/com/secondhand/user/UserService.java
  be/src/main/java/com/secondhand/user/dto/UserRegionsDto.java
  be/src/main/java/com/secondhand/user/login/LoginController.java
  be/src/main/java/com/secondhand/user/login/dto/JWTResponse.java
  be/src/main/java/com/secondhand/user/login/dto/LoggedInUser.java
Labels: 🧑‍💻 BE, ✨ feat, ♻️ refactor

#106 [FE] Not Found 페이지 생성 (404 error)
  fe/src/App.tsx
  fe/src/pages/NotFound/index.tsx
  fe/src/pages/NotFound/style.ts
Labels: 🧑‍💻 FE, ✨ feat

#119 [FE] Category 페이지의 header [뒤로] 버튼 기능 구현
  fe/src/components/common/Header/SearchHeader/style.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/Category/style.ts
  fe/src/styles/font.ts
Labels: 🧑‍💻 FE, ✨ feat

#126 [BE] 배포를 위한 PR
  be/src/main/java/com/secondhand/category/CategoryController.java
  be/src/main/java/com/secondhand/category/CategoryService.java
  be/src/main/java/com/secondhand/config/WebConfig.java
  be/src/main/java/com/secondhand/exception/GlobalExceptionHandler.java
  be/src/main/java/com/secondhand/fileupload/FileUploadController.java
  be/src/main/java/com/secondhand/interceptor/CreatePostInterceptor.java
  be/src/main/java/com/secondhand/interceptor/LoginInterceptor.java
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/PostService.java
  be/src/main/java/com/secondhand/post/dto/UpdatePostStateDto.java
  be/src/main/java/com/secondhand/post/entity/Badge.java
  be/src/main/java/com/secondhand/post/entity/Category.java
  be/src/main/java/com/secondhand/post/entity/PostMeta.java
  be/src/main/java/com/secondhand/post/repository/PostMetaRepository.java
  be/src/main/java/com/secondhand/post/repository/badge/BadgeRepository.java
  be/src/main/java/com/secondhand/post/repository/category/CategoryRepository.java
  be/src/main/java/com/secondhand/post/repository/category/CategoryRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/category/CategoryRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/interest/InterestRepository.java
  be/src/main/java/com/secondhand/post/repository/interest/InterestRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/interest/InterestRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/postdetail/PostDetailRepository.java
  be/src/main/java/com/secondhand/post/repository/postmeta/PostMetaRepository.java
  be/src/main/java/com/secondhand/post/repository/postmeta/PostMetaRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/postmeta/PostMetaRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/postphoto/PostPhotoRepository.java
  be/src/main/java/com/secondhand/post/repository/postphoto/PostPhotoRepositoryCustom.java
  be/src/main/java/com/secondhand/post/repository/postphoto/PostPhotoRepositoryImpl.java
  be/src/main/java/com/secondhand/post/validator/PostValidator.java
  be/src/main/java/com/secondhand/region/RegionService.java
  be/src/main/java/com/secondhand/region/dto/PostMyRegionDto.java
  be/src/main/java/com/secondhand/region/dto/RegionDto.java
  be/src/main/java/com/secondhand/region/entity/Region.java
  be/src/main/java/com/secondhand/region/repository/RegionRepository.java
  be/src/main/java/com/secondhand/region/validator/RegionValidator.java
  be/src/main/java/com/secondhand/user/UserController.java
  be/src/main/java/com/secondhand/user/UserService.java
  be/src/main/java/com/secondhand/user/dto/UserRegionsDto.java
  be/src/main/java/com/secondhand/user/entity/User.java
  be/src/main/java/com/secondhand/user/login/LoginController.java
  be/src/main/java/com/secondhand/user/login/dto/JWTResponse.java
  be/src/main/java/com/secondhand/user/login/dto/LoggedInUser.java
  be/src/test/java/com/secondhand/post/PostControllerTest.java
  be/src/test/java/com/secondhand/post/PostServiceTest.java
  be/src/test/java/com/secondhand/post/repository/postmeta/PostMetaRepositoryImplTest.java
  be/src/test/java/com/secondhand/post/repository/postmeta/PostMetaRepositoryTest.java
Labels: 🧑‍💻 BE

#128 [FE] NeighborhoodSetting에서 RegionSetting으로 변경
  fe/src/App.tsx
  fe/src/components/common/Header/HomeHeader/index.tsx
  fe/src/pages/NeighborhoodSetting/index.tsx
  fe/src/pages/RegionSetting/index.tsx
  fe/src/pages/RegionSetting/style.ts
Labels: 🧑‍💻 FE, ♻️ refactor

#125 [FE] Home 페이지에서 스크롤을 상단으로 이동하는 버튼
  fe/src/pages/Home/index.tsx
  fe/src/pages/Home/style.ts
Labels: 🧑‍💻 FE, ✨ feat

#121 [FE] 새상품 등록 탭바 뷰 구현
  README.md
  fe/src/assets/regionSetting.svg
  fe/src/components/common/Icon/index.tsx
  fe/src/constants/index.ts
  fe/src/pages/NewProduct/index.tsx
  fe/src/pages/NewProduct/style.js
Labels: 🧑‍💻 FE, ✨ feat, ♻️ refactor

#135 [FE] 데이터 형식 변환으로 로그인 로직 및 useFetch 수정
  fe/src/hooks/useFetch.ts
  fe/src/pages/LoginLoading/index.tsx
Labels: 🧑‍💻 FE, ♻️ refactor

#130 [FE] 동네 Modal의 [내 동네 설정하기] 기능 구현
  fe/src/components/common/Header/HomeHeader/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#136 [FE] 동네 설정 View
  fe/src/components/ProductListItem/style.ts
  fe/src/components/TabBar/style.ts
  fe/src/components/common/Button/style.ts
  fe/src/components/common/Header/HomeHeader/index.tsx
  fe/src/components/common/Header/HomeHeader/style.ts
  fe/src/components/common/Header/SalesHeader/style.ts
  fe/src/pages/Category/style.ts
  fe/src/pages/NewProduct/style.js
  fe/src/pages/RegionSetting/index.tsx
  fe/src/pages/RegionSetting/style.ts
  fe/src/styles/font.ts
  fe/src/utils/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#139 [FE] 이미지 업로드 버튼 뷰 구현
  fe/src/components/ImageIput/index.tsx
  fe/src/components/ImageIput/style.ts
  fe/src/pages/NewProduct/index.tsx
  fe/src/pages/NewProduct/style.ts
Labels: 🧑‍💻 FE, ✨ feat

#140 [BE] 2주차 리뷰 전체 반영
  be/src/main/java/com/secondhand/category/CategoryController.java
  be/src/main/java/com/secondhand/config/AWSConfig.java
  be/src/main/java/com/secondhand/config/JpaConfig.java
  be/src/main/java/com/secondhand/config/SwaggerConfig.java
  be/src/main/java/com/secondhand/config/WebConfig.java
  be/src/main/java/com/secondhand/exception/GlobalExceptionHandler.java
  be/src/main/java/com/secondhand/exception/login/ExpiredTokenException.java
  be/src/main/java/com/secondhand/exception/login/JwtTokenException.java
  be/src/main/java/com/secondhand/exception/login/ManipulatedTokenException.java
  be/src/main/java/com/secondhand/exception/login/NoAuthorizationException.java
  be/src/main/java/com/secondhand/exception/login/NoBearerException.java
  be/src/main/java/com/secondhand/exception/post/PostAuthorizationException.java
  be/src/main/java/com/secondhand/exception/post/PostOwnershipMismatchException.java
  be/src/main/java/com/secondhand/fileupload/FileUploadService.java
  be/src/main/java/com/secondhand/interceptor/LoginInterceptor.java
  be/src/main/java/com/secondhand/post/PostController.java
  be/src/main/java/com/secondhand/post/dto/PostDetailPageDto.java
  be/src/main/java/com/secondhand/post/dto/UpdatePostStateDto.java
  be/src/main/java/com/secondhand/post/entity/Category.java
  be/src/main/java/com/secondhand/post/entity/PostMeta.java
  be/src/main/java/com/secondhand/post/repository/category/CategoryRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/interest/InterestRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/postmeta/PostMetaRepositoryImpl.java
  be/src/main/java/com/secondhand/post/repository/postphoto/PostPhotoRepositoryImpl.java
  be/src/main/java/com/secondhand/post/validator/PostValidator.java
  be/src/main/java/com/secondhand/region/RegionController.java
  be/src/main/java/com/secondhand/region/repository/RegionRepositoryImpl.java
  be/src/main/java/com/secondhand/region/validator/RegionValidator.java
  be/src/main/java/com/secondhand/user/UserService.java
  be/src/main/java/com/secondhand/user/login/JwtUtil.java
  be/src/main/java/com/secondhand/user/login/LoginController.java
  be/src/main/java/com/secondhand/user/login/LoginService.java
  be/src/main/java/com/secondhand/user/login/dto/GithubToken.java
  be/src/main/resources/application.yml
Labels: 🧑‍💻 BE, ♻️ refactor

#143 [FE] api, path 상수 처리 및 env 처리
  fe/.gitignore
  fe/src/App.tsx
  fe/src/components/ProductList/index.tsx
  fe/src/components/TabBar/index.tsx
  fe/src/components/common/Header/HomeHeader/index.tsx
  fe/src/constants/iconName.ts
  fe/src/constants/index.ts
  fe/src/constants/path.ts
  fe/src/constants/requestUrl.ts
  fe/src/hooks/useFetch.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/CategoryDetail/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/LoginLoading/index.tsx
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/NotFound/index.tsx
  fe/src/pages/RegionSetting/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#144 [FE] 환경변수 설정
  fe/.gitignore
  fe/src/App.tsx
  fe/src/components/ProductList/index.tsx
  fe/src/components/TabBar/index.tsx
  fe/src/components/common/Header/HomeHeader/index.tsx
  fe/src/constants/iconName.ts
  fe/src/constants/index.ts
  fe/src/constants/path.ts
  fe/src/constants/requestUrl.ts
  fe/src/hooks/useFetch.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/CategoryDetail/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/LoginLoading/index.tsx
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/NotFound/index.tsx
  fe/src/pages/RegionSetting/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#154 [FE] 새상품 등록 페이지 이미지 업로드 및 뷰 구현
  fe/src/components/ImageIput/index.tsx
  fe/src/components/ImageIput/style.ts
  fe/src/pages/NewProduct/index.tsx
  fe/src/pages/NewProduct/style.ts
Labels: 🧑‍💻 FE, ✨ feat

#153 [FE] 상품 상세 페이지 View 완성
  fe/src/App.tsx
  fe/src/pages/ProductDetail/index.tsx
  fe/src/pages/ProductDetail/style.ts
Labels: 🧑‍💻 FE, ✨ feat

#156 [FE] usefetch 리팩토링
  fe/.eslintrc.json
  fe/src/App.tsx
  fe/src/components/ProductList/index.tsx
  fe/src/components/common/Header/HomeHeader/index.tsx
  fe/src/components/common/Header/index.tsx
  fe/src/context/userContext.tsx
  fe/src/hooks/useFetch.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/CategoryDetail/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/LoginLoading/index.tsx
  fe/src/pages/RegionSetting/index.tsx
  fe/src/utils/index.tsx
Labels: 🧑‍💻 FE, ♻️ refactor

#158 [FE] 상품 상세 페이지 View
  fe/src/components/ProductListItem/index.tsx
  fe/src/pages/ProductDetail/index.tsx
  fe/src/pages/ProductDetail/style.ts
  fe/src/utils/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#163 [FE] release-fe에 fe 브런치 merge
  fe/.eslintrc.json
  fe/src/App.tsx
  fe/src/components/ImageIput/index.tsx
  fe/src/components/ImageIput/style.ts
  fe/src/components/ProductList/index.tsx
  fe/src/components/ProductListItem/index.tsx
  fe/src/components/common/Header/HomeHeader/index.tsx
  fe/src/components/common/Header/index.tsx
  fe/src/context/userContext.tsx
  fe/src/hooks/useFetch.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/CategoryDetail/index.tsx
  fe/src/pages/Home/index.tsx
  fe/src/pages/LoginLoading/index.tsx
  fe/src/pages/NewProduct/index.tsx
  fe/src/pages/NewProduct/style.ts
  fe/src/pages/ProductDetail/index.tsx
  fe/src/pages/ProductDetail/style.ts
  fe/src/pages/RegionSetting/index.tsx
  fe/src/utils/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#164 [FE] release-fe에 fe merge
  fe/src/hooks/useFetch.ts
Labels: 🧑‍💻 FE

#161 [FE] 상세 페이지에 해당 상품에 관한 데이터를 화면에 표시한다.
  fe/src/App.tsx
  fe/src/assets/fullLike.svg
  fe/src/components/ProductListItem/index.tsx
  fe/src/components/common/Icon/index.tsx
  fe/src/constants/iconName.ts
  fe/src/constants/path.ts
  fe/src/pages/ProductDetail/index.tsx
  fe/src/pages/ProductDetail/style.ts
  fe/src/utils/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#168 [FE] 카테고리 버튼 구현
  fe/src/assets/chevronRight.svg
  fe/src/components/InputTitle/index.tsx
  fe/src/components/InputTitle/style.ts
  fe/src/components/common/Icon/index.tsx
  fe/src/constants/iconName.ts
  fe/src/pages/NewProduct/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#175 [FE] api base_url 수정
  fe/src/constants/requestUrl.ts
Labels: 🧑‍💻 FE, ♻️ refactor

#176 [FE] 상품 상세 페이지 Header의 [더보기] 버튼 기능 #171
  fe/src/components/ProductDetail/ProductDetailHeader/index.tsx
  fe/src/components/ProductDetail/ProductDetailHeader/style.ts
  fe/src/components/ProductDetail/ProductDetailMain/index.tsx
  fe/src/components/ProductDetail/ProductDetailMain/style.ts
  fe/src/components/common/Popup/Popup.stories.tsx
  fe/src/components/common/Popup/index.tsx
  fe/src/components/common/Popup/style.ts
  fe/src/pages/ProductDetail/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#178 [FE] 로그인 한 상태일 경우, 내 계정 페이지에서 사용자 정보 표시 및 로그아웃 버튼 기능 구현
  fe/src/context/userContext.tsx
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/MyAccount/style.ts
Labels: 🧑‍💻 FE, ✨ feat

#180 [FE] Dropdown 공통 컴포넌트 생성
  fe/src/components/ProductDetail/ProductDetailMain/index.tsx
  fe/src/components/ProductDetail/ProductDetailMain/style.ts
  fe/src/components/common/Dropdown/index.tsx
  fe/src/components/common/Dropdown/style.ts
  fe/src/components/common/Header/HomeHeader/index.tsx
  fe/src/components/common/Header/HomeHeader/style.ts
  fe/src/utils/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#194 [FE] Spinner 공통 컴포넌트와 Loading 컴포넌트 구현
  fe/src/assets/second-hand-logo.png
  fe/src/components/Loading/index.tsx
  fe/src/components/Loading/style.ts
  fe/src/components/ProductList/index.tsx
  fe/src/components/ProductList/style.ts
  fe/src/components/common/Spinner/Spinner.stories.tsx
  fe/src/components/common/Spinner/index.tsx
  fe/src/components/common/Spinner/style.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/LoginLoading/index.tsx
  fe/src/pages/LoginLoading/style.ts
  fe/src/pages/ProductDetail/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#198 [FE] release fe로 merge
  fe/src/pages/NewProduct/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#201 feat: 시간 표시 1 ~ 24를 0 ~ 23으로 범위 수정
  be/src/main/java/com/secondhand/mapper/JacksonLocalDateTimeConfig.java
Labels: 🐛 fix, 🧑‍💻 BE

#203 [FE] 상품 등록 후 응답이 success면 상세 페이지로 이동
  fe/src/pages/NewProduct/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#200 [FE] 인증이 되지 않은 사용자일 경우, "로그인 후 이용 가능합니다."라는 경고 메시지와 함께 [홈 페이지로 이동]버튼과 [로그인 페이지]버튼이 있는 Popup창이 뜬다.
  fe/src/App.tsx
  fe/src/components/PrivateRoutes/index.tsx
  fe/src/components/PrivateRoutes/style.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/MyAccount/style.ts
Labels: 🧑‍💻 FE, ✨ feat

#204 [FE] release-fe 브런치에 fe 브런치 merge
  fe/src/App.tsx
  fe/src/components/PrivateRoutes/index.tsx
  fe/src/components/PrivateRoutes/style.ts
  fe/src/pages/Category/index.tsx
  fe/src/pages/MyAccount/index.tsx
  fe/src/pages/MyAccount/style.ts
  fe/src/pages/NewProduct/index.tsx
Labels: 🧑‍💻 FE

#205 fix: 애플리케이션 재시작
  be/src/main/java/com/secondhand/post/PostController.java
Labels: 🐛 fix, 🧑‍💻 BE

#207 [FE] 완료 버튼 눌렀을 때 post 요청 계속 가는 문제 해결 (#206)
  fe/src/pages/NewProduct/index.tsx
Labels: 🐛 fix, 🧑‍💻 FE

#209 [FE] 상품 상세 페이지에서 [<] 버튼 기능
  fe/src/components/ProductDetail/ProductDetailHeader/index.tsx
  fe/src/pages/NewProduct/index.tsx
Labels: 🧑‍💻 FE, ✨ feat

#210 [FE] release-fe 에 merge
  fe/src/components/ProductDetail/ProductDetailHeader/index.tsx
  fe/src/pages/NewProduct/index.tsx
Labels: 🧑‍💻 FE
